# Generated by Django 5.2.1 on 2025-05-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrequest',
            old_name='venue',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='expected_attendees',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='poster',
        ),
    ]
